import { User, Book, Order, Review } from '../types/database';

export const users: User[] = [
  {
    id: '1',
    email: 'admin@bookora.com',
    password: 'admin123',
    name: 'Admin User',
    role: 'admin',
    status: 'active',
    createdAt: new Date('2024-01-01'),
    updatedAt: new Date('2024-01-01'),
  },
  {
    id: '2',
    email: 'seller@books.com',
    password: 'seller123',
    name: 'John Publisher',
    role: 'seller',
    status: 'active',
    companyName: 'Premium Books Publishing',
    companyVerified: true,
    createdAt: new Date('2024-01-15'),
    updatedAt: new Date('2024-01-15'),
  },
  {
    id: '3',
    email: 'buyer@email.com',
    password: 'buyer123',
    name: 'Jane Reader',
    role: 'buyer',
    status: 'active',
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
];

export const books: Book[] = [
  {
    id: '1',
    sellerId: '2',
    title: 'The Great Gatsby',
    author: 'F. Scott Fitzgerald',
    isbn: '978-0-7432-7356-5',
    description: 'A classic novel of the Jazz Age, exploring themes of wealth, love, and the American Dream.',
    genre: 'Classic Fiction',
    publisher: 'Scribner',
    price: 15.99,
    stock: 50,
    imageUrl: 'https://images.unsplash.com/photo-1544947950-fa07a98d237f?w=400',
    publicationYear: 1925,
    language: 'English',
    pages: 180,
    createdAt: new Date('2024-02-01'),
    updatedAt: new Date('2024-02-01'),
  },
  {
    id: '2',
    sellerId: '2',
    title: 'To Kill a Mockingbird',
    author: 'Harper Lee',
    isbn: '978-0-06-112008-4',
    description: 'A gripping tale of racial injustice and childhood innocence in the American South.',
    genre: 'Classic Fiction',
    publisher: 'Harper Perennial',
    price: 14.99,
    stock: 35,
    imageUrl: 'https://images.unsplash.com/photo-1512820790803-83ca734da794?w=400',
    publicationYear: 1960,
    language: 'English',
    pages: 324,
    createdAt: new Date('2024-02-02'),
    updatedAt: new Date('2024-02-02'),
  },
  {
    id: '3',
    sellerId: '2',
    title: '1984',
    author: 'George Orwell',
    isbn: '978-0-452-28423-4',
    description: 'A dystopian masterpiece about totalitarianism and surveillance.',
    genre: 'Science Fiction',
    publisher: 'Penguin Books',
    price: 16.99,
    stock: 42,
    imageUrl: 'https://images.unsplash.com/photo-1495446815901-a7297e633e8d?w=400',
    publicationYear: 1949,
    language: 'English',
    pages: 328,
    createdAt: new Date('2024-02-03'),
    updatedAt: new Date('2024-02-03'),
  },
  {
    id: '4',
    sellerId: '2',
    title: 'Pride and Prejudice',
    author: 'Jane Austen',
    isbn: '978-0-14-143951-8',
    description: 'A romantic novel exploring manners, marriage, and morality in Georgian England.',
    genre: 'Romance',
    publisher: 'Penguin Classics',
    price: 12.99,
    stock: 28,
    imageUrl: 'https://images.unsplash.com/photo-1543002588-bfa74002ed7e?w=400',
    publicationYear: 1813,
    language: 'English',
    pages: 432,
    createdAt: new Date('2024-02-04'),
    updatedAt: new Date('2024-02-04'),
  },
];

export const orders: Order[] = [
  {
    id: '1',
    buyerId: '3',
    items: [
      {
        bookId: '1',
        sellerId: '2',
        quantity: 1,
        price: 15.99,
      }
    ],
    totalAmount: 15.99,
    status: 'pending',
    shippingAddress: {
      street: '123 Main St',
      city: 'New York',
      state: 'NY',
      postalCode: '10001',
      country: 'USA',
    },
    createdAt: new Date('2024-02-10'),
    updatedAt: new Date('2024-02-10'),
  }
];

export const reviews: Review[] = [
  {
    id: '1',
    bookId: '1',
    buyerId: '3',
    sellerId: '2',
    rating: 5,
    comment: 'Отличная книга! Рекомендую всем любителям классики.',
    createdAt: new Date('2024-02-15'),
  }
];
